### ISSUE TITLE
Authors not in the data file are not listed

### ISSUE THREAD

**Issue by JamesWClark** [RockhurstHS/STEAM-Blog#13]
It would probably be easier to manage if we allowed authors to get listed who are not in the data file or "Who We Are" profile section of the steam blog.

**Comment by gowsley** [comment]
I agree.

Sent from my iPhone

On Nov 20, 2016, at 1:07 AM, J.W. Clark notifications@github.com wrote:

It would probably be easier to manage if we allowed authors to get listed
who are not in the data file or "Who We Are" profile section of the steam
blog.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
https://github.com/RockhurstHS/STEAM-Blog/issues/13, or mute the thread

**Comment by JamesWClark** [comment]
Fixed and tested working with Miles Wood and Harrison Oest, neither of whom are listed in people.yml
